name: Checkbox

on:
  workflow_dispatch:
    inputs:
      test_checkbox:
        description: 'Test Checkbox'
        type: boolean
jobs:
  validate_deployment_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          
      - name: Test 1
        if: ${{ fromJSON(github.event.inputs.test_checkbox) }}
        run: |
          echo '1'
          
          
      - name: Test 2
        if: ${{ !fromJSON(github.event.inputs.test_checkbox) }}
        run: |
          echo '2'
          
      - name: Test 3
        if: ${{ fromJSON(github.event.inputs.test_checkbox)  == true }}
        run: |
          echo '3'
          
      - name: Test 4
        if: ${{ fromJSON(github.event.inputs.test_checkbox)  == false }}
        run: |
          echo '4'


